import { act, renderHook, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { useAISearch } from "./useAISearch";
import { AIServiceError } from "@/services/ai";
import * as aiModule from "@/services/ai";
import type { AIResponse, SearchPayload } from "@/shared/contracts/ai";

// Helpers ---------------------------------------------------------------

async function* okStream(): AsyncGenerator<AIResponse<SearchPayload>, void, void> {
  yield {
    id: "ok",
    status: "complete",
    disclaimer: "Generated by Novatrix IP. Not legal advice.",
    citations: [],
    data: { summary: "ok", precedents: [], timeline: [] },
  };
}

function failingStream(code: "network" | "validation" | "internal", message: string) {
  return async function* (): AsyncGenerator<AIResponse<SearchPayload>, void, void> {
    // Yield-before-throw keeps lint happy and matches real provider behaviour
    // where the first chunk arrives before the connection drops.
    if (false as boolean) yield undefined as never;
    throw new AIServiceError(code, message);
  };
}

describe("useAISearch retry-with-backoff", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("retries transient network errors and then succeeds", async () => {
    let calls = 0;
    vi.spyOn(aiModule.aiService, "searchStream").mockImplementation(() => {
      calls += 1;
      if (calls <= 2) return failingStream("network", `transient ${calls}`)();
      return okStream();
    });

    const { result } = renderHook(() => useAISearch({ maxRetries: 2, backoffBaseMs: 1 }));

    act(() => {
      result.current.submit({ query: "x", jurisdictions: [], topics: [] });
    });

    await waitFor(
      () => {
        expect(result.current.state.status).toBe("success");
      },
      { timeout: 2000 },
    );
    expect(calls).toBe(3);
  });

  it("does not retry validation errors", async () => {
    let calls = 0;
    vi.spyOn(aiModule.aiService, "searchStream").mockImplementation(() => {
      calls += 1;
      return failingStream("validation", "bad request")();
    });

    const { result } = renderHook(() => useAISearch({ maxRetries: 3, backoffBaseMs: 1 }));
    act(() => {
      result.current.submit({ query: "x", jurisdictions: [], topics: [] });
    });

    await waitFor(() => {
      expect(result.current.state.status).toBe("error");
    });
    expect(calls).toBe(1);
    if (result.current.state.status === "error") {
      expect(result.current.state.error.code).toBe("validation");
      expect(result.current.state.attempts).toBe(1);
    }
  });

  it("gives up after maxRetries on persistent transient errors", async () => {
    let calls = 0;
    vi.spyOn(aiModule.aiService, "searchStream").mockImplementation(() => {
      calls += 1;
      return failingStream("network", "down")();
    });

    const { result } = renderHook(() => useAISearch({ maxRetries: 2, backoffBaseMs: 1 }));
    act(() => {
      result.current.submit({ query: "x", jurisdictions: [], topics: [] });
    });

    await waitFor(
      () => {
        expect(result.current.state.status).toBe("error");
      },
      { timeout: 2000 },
    );
    expect(calls).toBe(3);
    if (result.current.state.status === "error") {
      expect(result.current.state.error.code).toBe("network");
      expect(result.current.state.attempts).toBe(3);
    }
  });
});
