import { z } from "zod";
import { jurisdictions } from "@/shared/design/tokens";

export const JurisdictionSchema = z.enum(jurisdictions);

export const CitationSchema = z.object({
  id: z.string(),
  title: z.string(),
  source: z.string().url().optional(),
  jurisdiction: JurisdictionSchema.optional(),
  date: z.string().optional(),
});
export type Citation = z.infer<typeof CitationSchema>;

export const AIStatus = z.enum(["streaming", "complete", "error"]);
export type AIStatus = z.infer<typeof AIStatus>;

/**
 * Canonical AI response envelope. Every AI endpoint (mock or real) MUST conform.
 * UI binds to `status` to pick render state; never to provider-specific fields.
 */
export const AIResponseSchema = <T extends z.ZodTypeAny>(data: T) =>
  z.object({
    id: z.string(),
    status: AIStatus,
    data,
    citations: z.array(CitationSchema).default([]),
    jurisdiction: JurisdictionSchema.optional(),
    disclaimer: z.string(),
  });

export type AIResponse<T> = {
  id: string;
  status: AIStatus;
  data: T;
  citations: Citation[];
  jurisdiction?: z.infer<typeof JurisdictionSchema>;
  disclaimer: string;
};

/* ------------------------------------------------------------------ */
/* Feature payloads                                                    */
/* ------------------------------------------------------------------ */

export const SearchRequestSchema = z.object({
  query: z.string().min(1).max(2000),
  jurisdictions: z.array(JurisdictionSchema).max(8).default([]),
  topics: z.array(z.string()).max(16).default([]),
});
export type SearchRequest = z.infer<typeof SearchRequestSchema>;

export const PrecedentRefSchema = z.object({
  id: z.string(),
  caption: z.string(),
  year: z.number().int().optional(),
  jurisdiction: JurisdictionSchema.optional(),
  source: z.string().url().optional(),
});

export const TimelineEventSchema = z.object({
  date: z.string(),
  label: z.string(),
});

export const SearchPayloadSchema = z.object({
  summary: z.string(),
  precedents: z.array(PrecedentRefSchema).default([]),
  timeline: z.array(TimelineEventSchema).default([]),
});
export type SearchPayload = z.infer<typeof SearchPayloadSchema>;

/* ------------------------------------------------------------------ */
/* Theory                                                              */
/* ------------------------------------------------------------------ */

export const TheoryDepthSchema = z.enum(["beginner", "intermediate", "advanced"]);
export type TheoryDepth = z.infer<typeof TheoryDepthSchema>;

export const TheoryRequestSchema = z.object({
  query: z.string().min(1).max(2000),
  depth: TheoryDepthSchema.default("intermediate"),
});
export type TheoryRequest = z.infer<typeof TheoryRequestSchema>;

export const TheoryThinkerSchema = z.object({
  name: z.string(),
  era: z.string(),
  contribution: z.string(),
});

export const TheoryFurtherReadingSchema = z.object({
  label: z.string(),
  url: z.string().url().optional(),
});
export type TheoryFurtherReading = z.infer<typeof TheoryFurtherReadingSchema>;

export const TheoryPayloadSchema = z.object({
  depth: TheoryDepthSchema,
  thesis: z.string(),
  explanation: z.string(),
  thinkers: z.array(TheoryThinkerSchema).default([]),
  furtherReading: z.array(TheoryFurtherReadingSchema).default([]),
});
export type TheoryPayload = z.infer<typeof TheoryPayloadSchema>;

export const DEFAULT_DISCLAIMER =
  "Generated by Novatrix IP for informational purposes only. Not legal advice; no attorney–client relationship is formed.";
