import { useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Motion } from "@/shared/ui/Motion";
import { WorldMap } from "@/features/landing/WorldMap";
import { TOPICS } from "@/features/maps/topics";

export function MapsPage() {
  const [params, setParams] = useSearchParams();
  const initialId = params.get("topic") ?? TOPICS[0]?.id ?? "copyright";
  const [activeId, setActiveId] = useState<string>(initialId);

  const active = useMemo(() => TOPICS.find((t) => t.id === activeId) ?? TOPICS[0]!, [activeId]);

  function selectTopic(id: string) {
    setActiveId(id);
    const next = new URLSearchParams(params);
    next.set("topic", id);
    setParams(next, { replace: true });
  }

  return (
    <section className="relative">
      <div className="container py-16 md:py-24">
        <Motion variant="rise">
          <header className="mb-10 flex max-w-3xl flex-col gap-3">
            <p className="text-[11px] uppercase tracking-[0.18em] text-ink-tertiary">Legal Maps</p>
            <h1 className="text-balance font-display text-headline font-medium tracking-tight">
              Cinematic atlases of the legal world.
            </h1>
            <p className="text-base text-ink-secondary">
              Toggle topics to see jurisdictional intensity. Hover a node for doctrine; the same map
              renders copyright, AI law, trademark systems, and dispute hotspots.
            </p>
          </header>
        </Motion>

        <Motion variant="rise" delay="fast">
          <div
            role="tablist"
            aria-label="Map topic"
            className="mb-6 flex flex-wrap items-center gap-2"
          >
            {TOPICS.map((t) => {
              const isActive = t.id === active.id;
              return (
                <button
                  key={t.id}
                  role="tab"
                  type="button"
                  aria-selected={isActive}
                  aria-controls={`map-panel-${t.id}`}
                  id={`map-tab-${t.id}`}
                  onClick={() => selectTopic(t.id)}
                  className={[
                    "rounded-full border px-4 py-1.5 text-sm transition-colors duration-fast",
                    isActive
                      ? "border-accent-electric/60 bg-accent-electric/15 text-ink-primary"
                      : "border-hairline bg-surface-1/40 text-ink-secondary hover:text-ink-primary",
                  ].join(" ")}
                >
                  {t.label}
                </button>
              );
            })}
          </div>
        </Motion>

        <Motion variant="rise" delay="base">
          <div
            id={`map-panel-${active.id}`}
            role="tabpanel"
            aria-labelledby={`map-tab-${active.id}`}
            className="grid gap-8 lg:grid-cols-[1.6fr_1fr]"
          >
            <div className="overflow-hidden rounded-2xl border border-hairline bg-surface-1/30 p-4 shadow-elevated">
              <WorldMap
                key={active.id}
                highlight={active.highlight}
                intensity={active.intensity}
                ariaLabel={`World map highlighting ${active.label.toLowerCase()} across ${active.highlight.length} jurisdictions`}
              />
            </div>
            <aside className="flex flex-col gap-5 rounded-2xl border border-hairline bg-surface-1/40 p-6 shadow-elevated backdrop-blur-glass">
              <div>
                <p className="text-[11px] uppercase tracking-[0.18em] text-ink-tertiary">
                  {active.eyebrow}
                </p>
                <h2 className="mt-2 font-display text-title font-medium tracking-tight text-ink-primary">
                  {active.label}
                </h2>
                <p className="mt-3 text-sm text-ink-secondary">{active.description}</p>
              </div>
              <div className="border-t border-hairline pt-5">
                <p className="text-[11px] uppercase tracking-[0.18em] text-ink-tertiary">
                  Highlights
                </p>
                <ul className="mt-3 flex flex-col gap-3">
                  {active.notes.map((n) => (
                    <li key={n.jurisdiction} className="flex gap-3">
                      <span className="mt-0.5 inline-flex h-6 min-w-[2.5rem] items-center justify-center rounded-md border border-hairline bg-surface-1 px-2 font-mono text-[10px] uppercase tracking-[0.18em] text-accent-electric">
                        {n.jurisdiction}
                      </span>
                      <span className="text-sm text-ink-secondary">{n.note}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <p className="border-t border-hairline pt-5 text-xs text-ink-tertiary">
                Generated by Novatrix IP. Not legal advice; jurisdictional summaries are directional
                and not exhaustive.
              </p>
            </aside>
          </div>
        </Motion>
      </div>
    </section>
  );
}
